site_name: A Peek Into Ballance Mapping
site_description: 'The supplementary manual for Ballance mapping in Blender'
site_author: 'yyc12345'
site_url: 'https://yyc12345.github.io/A-Peek-Into-Ballance-Mapping/'
copyright: 'Text is available under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>.'

nav:
  - 「    」: 'index.md'
  - English:
    - 'Preface': 'en/index.md'
  - 简体中文:
    - '序言': 'zh-cn/index.md'
    - '渐进式制图教程':
      - '你的第一张自制地图': 'zh-cn/tutorial/your-first-map.md'
      - '最小的关卡': 'zh-cn/tutorial/smallest-level.md'
      - '第一小节：拼接路面': 'zh-cn/tutorial/sector-1.md'
      - '第二小节：构建钢轨': 'zh-cn/tutorial/sector-2.md'
      - '第三小节：放置机关': 'zh-cn/tutorial/sector-3.md'
      - '装饰与死亡区': 'zh-cn/tutorial/decorations-and-depth-test-cube.md'
      - '清理与发布': 'zh-cn/tutorial/clean-and-release.md'
    - 'Ballance 制图概要':
      - '自制地图概述': 'zh-cn/mapping/introduction.md'
      - '工具安装与配置': 'zh-cn/mapping/installations.md'
      - '归组': 'zh-cn/mapping/grouping.md'
      - '钢轨参数': 'zh-cn/mapping/rail-parameter.md'
      - '贴图文件的保存格式': 'zh-cn/mapping/texture-option.md'
    - 'Blender 制图手册':
      - 'Blender 基础操作指南': 'zh-cn/blender/basic-manual.md'
      - '合并顶点注意事项': 'zh-cn/blender/merge-vertices.md'
      - 'Blender 放样方法': 'zh-cn/blender/sampling.md'
      - '吸附功能详解': 'zh-cn/blender/snapping.md'
      - '梨栠式拖动创建': 'zh-cn/blender/liren-drag.md'
      - '禁止缩放物理化的物体': 'zh-cn/blender/no-scaled-physicalized-object.md'
      - '无用物体清理': 'zh-cn/blender/unused-object.md'
      - '编辑材质': 'zh-cn/blender/modify-material.md'
    - '进阶操作指南':
      - '放样制作钢轨': 'zh-cn/advance/sampling-rail.md'
      - '放样制作路面': 'zh-cn/advance/sampling-floor.md'
    - '故障排除':
      - 'Blender 资产相关问题': 'zh-cn/trouble-shooting/blender-assets.md'
      - '路面发黑': 'zh-cn/trouble-shooting/black.md'
      - '翻面': 'zh-cn/trouble-shooting/flip.md'
      - '路面影子问题': 'zh-cn/trouble-shooting/shadow.md'
      - '柱子不断问题': 'zh-cn/trouble-shooting/transparent-column.md'
      - 'Stopper 没有声音': 'zh-cn/trouble-shooting/stopper-sound.md'
      - '光源': 'zh-cn/trouble-shooting/light.md'
    - '从 3ds MAX 迁移': 'zh-cn/migrate-from-max.md'

theme:
  # name: readthedocs
  # include_homepage_in_sidebar: false
  name: material
  language: en
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

extra:
  alternate:
    - name: English
      link: /A-Peek-Into-Ballance-Mapping/en/
      lang: en
    - name: 简体中文
      link: /A-Peek-Into-Ballance-Mapping/zh-cn/
      lang: zh

markdown_extensions:
  - admonition
  - toc:
      permalink: '#'
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
